name: DEPLOYMENT

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]  # You may adjust the Node.js version as needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
           ${{ runner.os }}-node-

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

          
      - name: Remove node_modules and package-lock.json
        run: |
          rm -rf node_modules
          rm -f package-lock.json


      - name: Install Dependencies
        run: |
          npm install
          # sudo npm cache clean -f
          # sudo npm install -g n
          # sudo n latest
          # sudo rm -rf node_modules package-lock.json
          # sudo npm install

      - name: Build Amplify App
        run: npm run-script build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAZMKFPOEN2LXJLTVS
          aws-secret-access-key: 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
          aws-region: ap-south-1 

      - name: Configure Amplify CLI
        run: npm install -g @aws-amplify/cli  # Corrected the installation command

      - name: Initialize Amplify Environment
        run: amplify init --app git@github.com:softobiz-vishwajeet/react-coffeelove.git --yes
             #amplify init --app git@github.com:myGHUSER/myAPP.git --yes

      - name: Deploy to Amplify
        run: amplify publish --yes























# name: Deploy to AWS Amplify

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     name: Deploy to AWS Amplify
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [18.x]

#     steps:
#     - uses: actions/checkout@v1

#     - name: use node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}

#     - name: Install Amplify CLI
#       run: npm install -g @aws-amplify/cli

#     - name: Configure Amplify
#       run: |
#         amplify configure
#       env:
#         AWS_ACCESS_KEY_ID: AKIAZMKFPOEN2LXJLTVS                             #${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: 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    #${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         AWS_REGION: ap-south-1 

#     - name: Initialize Amplify
#       run: amplify pull --appId d1m8t2tw7g1zgy --envName prod
#       env:
#         AWS_ACCESS_KEY_ID: AKIAZMKFPOEN2LXJLTVS                           #${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: 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   #${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         AWS_REGION: ap-south-1                                          # ${{ secrets.AWS_REGION }}
#       # run: amplify init --appId ${{ secrets.AMPLIFY_APP_ID }} --envName prod

#     - name: Execute Custom Commands
#       run: |
#         npm install -g npm-check-updates
#         ncu -u
#         npm install
#         npm run build
#         # npm install
#         # npm run build
#         # echo "Custom commands before Amplify"

#     - name: Execute Additional Custom Commands
#       run: |
#         echo "Custom commands after Amplify"
    
#     - name: Deploy with Amplify
#       run: |
#         ls -la
#         cd amplify
#         ls -lRa
#         amplify publish
#       env:
#         AWS_ACCESS_KEY_ID: AKIAZMKFPOEN2LXJLTVS                             #${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: 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    #${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         AWS_REGION: ap-south-1                                             #${{ secrets.AWS_REGION }}




























    
