name: Mirror GitHub To CodeCommit

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAZMKFPOEN2LXJLTVS #${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: 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 #${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Sync up to CodeCommit
        uses: tsgit18/sync-up-to-codecommit-action@v1
        with:
          repository_name: poc-repo
          aws_region: ap-south-1
