name: Mirror GitHub to CodeCommit

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Install required packages
      run: sudo apt-get install -y gridsite-clients
      

    - name: Mirror repository
      run: |
        git remote set-url --push origin https://${{ secrets.AWS_GIT_USERNAME }}:${{ secrets.AWS_GIT_PASSWORD }}@${{ secrets.AWS_REPO_URL }}
        git push --mirror origin
        # git clone --mirror https://github.com/softobiz-vishwajeet/react-coffeelove.git repo-mirror
        # cd repo-mirror
        # git remote set-url --push origin https://${{ secrets.AWS_GIT_USERNAME }}:${{ secrets.AWS_GIT_PASSWORD }}@${{ secrets.AWS_REPO_URL }}
        # git push --mirror origin
      env:
        #AZURE_REPO_URL: github.com/softobiz-vishwajeet/react-coffeelove.git   #${{ secrets.AZURE_REPO_URL }}
        #AZURE_GIT_USERNAME: softobiz-vishwajeet                             # ${{ secrets.AZURE_GIT_USERNAME }}
        #AZURE_GIT_PASSWORD: ${{ secrets.AZURE_GIT_PASSWORD }}
        AWS_REPO_URL: git-codecommit.ap-south-1.amazonaws.com/v1/repos/poc-repo #${{ secrets.AWS_REPO_URL }}
        AWS_GIT_USERNAME: test-user-at-644927680795                      #${{ secrets.AWS_GIT_USERNAME }}
        AWS_GIT_PASSWORD: G2XMvO2t4AhgtGRk7O2t0FfV6mNCgGm6wG8O5ehO6qk=  #${{ secrets.AWS_GIT_PASSWORD }}



#https://github.com/softobiz-vishwajeet/react-coffeelove.git

#https://${{ secrets.AZURE_GIT_USERNAME }}@${{ secrets.AZURE_REPO_URL }} repo-mirror
